import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import MainContextProvider from "@/context/MainContextProvider";
import { ThemeProvider } from "@/components/common/theme-provider";
import MainLayout from "@/components/common/MainLayout";
import { Toaster } from "@/components/ui/toaster";
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MainContextProvider>
            <MainLayout>{children}</MainLayout>
            <Toaster />
          </MainContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
